jobs:
- job: deploy
  dependsOn: infrastructure
  displayName: "Deploying To Azure"
  continueOnError: false
  steps:
  - task: DownloadBuildArtifacts@1
    displayName: 'Download Build Artifacts'
    inputs:
      buildType: 'current'
      downloadType: 'specific'
      itemPattern: '**/*.zip'
      downloadPath: '$(System.ArtifactsDirectory)'
  - task: AzureCLI@2
    displayName: 'Deploy Web Job'
    inputs:
      azureSubscription: ''
      scriptType: ps
      scriptLocation: inlineScript
      inlineScript: |
        az webapp deployment source config-zip `
        --resource-group $(app_name)-$(env)-rg `
        --name $(app_name)-worker-$(env) `
        --src $(System.ArtifactsDirectory)/drop/src.zip